export const LABELS = [
  "MV1_All time mango",
  "MV2_Alphonso",
  "MV3_Athimadhuram",
  "MV4_Banglora",
  "MV5_Benisha",
  "MV6_Bhastara",
  "MV7_Black Mango",
  "MV8_Chakrakuti",
  "MV9_Chandura",
  "MV10_Cherukurasam",
  "MV11_Daseri",
  "MV12_Himam Pasand",
  "MV13_Kalapedu",
  "MV14_Kesari",
  "MV15_Khadar",
  "MV16_Malaguba",
  "MV17_Mallika",
  "MV18_Miyazaki",
  "MV19_Namdac",
  "MV20_Neelam",
  "MV21_Noor jahan",
  "MV22_Peddarasam",
  "MV23_Punasa",
  "MV24_Red Ivory",
  "MV25_Rumani",
];